apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: acme-metaflow
  name: workflowtaskresults-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: acme-metaflow
roleRef:
  kind: Role
  name: workflowtaskresults-role
  apiGroup: rbac.authorization.k8s.io