apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: acme-metaflow
  name: workflowtaskresults-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch", "update", "get", "list", "watch"]